name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install
        run: yarn

  build:
    name: Build the project
    runs-on: ubuntu-latest
    needs:
      - dependencies

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install
        run: yarn

      - name: Build
        run: yarn run build

  linters:
    name: Run linter checks
    runs-on: ubuntu-latest
    needs:
      - dependencies

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install
        run: yarn

      - name: Lint
        run: yarn run linters

  deploy:
    name: Deploy project build
    runs-on: ubuntu-latest
    needs:
      - dependencies
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install
        run: yarn

      - name: Deploy
        run: yarn run deploy
